### ISSUE TITLE
ZeroDivisionError: float division by zero from sparse data set

### ISSUE THREAD

**Issue by NancyAb** [leapingllamas/medium_posts#1]
Hello - thanks so much for sharing a weighted means. I have an area with little weight and I think it may be causing problems. I have been unable to trap the error using "try/except" in the code. Would you have any advice on how to proceed? 

` points,centers,it_num = data_weighted_kmeans(points,centers,k)

points,centers,it_num = data_weighted_kmeans(points,centers,k)
C:\temp\DEF-GEO\weightedmeans\data_weighted_kmeans.py:106: RuntimeWarning: invalid value encountered in true_divide
  c["coords"] /= c['w']
Traceback (most recent call last):

  File "<ipython-input-2-4981a680c9f0>", line 1, in <module>
    points,centers,it_num = data_weighted_kmeans(points,centers,k)

  File "C:\temp\DEF-GEO\weightedmeans\data_weighted_kmeans.py", line 131, in data_weighted_kmeans
    distsq[cj]= ( (distance(lat1,long1,lat2,long2)**2) * c['w'] ) / ( c['w'] + p['w'] )

ZeroDivisionError: float division by zero`

Nancy.

**Comment by andhint** [comment]
Not the author, but I would add a small value to all your observations with a value of 0

**Comment by NancyAb** [comment]
I *believe* the problem is that the centers move to find the optimal centroids so they may end up not having any members which results in division by zero. I do not include any observations with a weight of zero.

**Comment by andhint** [comment]
Ahh ok, I'm not sure how to help then
